parameters:
#    bsg_game.example.class: Bsg\GameBundle\Example

services:
#    bsg_game.example:
#        class: %bsg_game.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
